---
title: "Pardalis effect"
author: "Vanesa Bejarano Alegre"
date: "10/26/2020"
output: word_document
---
#Prepare data

## Install and load packages
```{r Packages, message=FALSE, warning=FALSE}

rm(list= ls())  #clean all before to start

library(tidyverse)
library(here)
library(tidyverse)
library(sf)
library(raster)
library(ecospat)
library(rnaturalearth)
library(rgdal)
library(ordinal)
library(ggstatsplot)

```

### R Packages
**_Tidyverse_** is a collection of R-packages designed for data science.

## Set working directory and load data

```{r Download, message=FALSE, warning=FALSE}

download.file(url = "https://esajournals.onlinelibrary.wiley.com/action/downloadSupplement?doi=10.1002%2Fecy.3128&file=ecy3128-sup-0001-DataS1.zip",
              destfile = here::here("01_communities", "ecy3128-sup-0001-DataS1.zip"), mode = "wb")

# unzip
unzip(zipfile = here::here("01_communities", "ecy3128-sup-0001-DataS1.zip"),
      exdir = here::here("01_communities"))

carnivores <- readr::read_csv(here::here("01_communities", "NEOTROPICAL_CARNIVORES_DATASET_2020-04.csv"))

landcover <- raster(here::here("02_raster",  "mapbiomas_1km.tif")) 
```

### Mehod filter (Camera trap)
First we know the levels that the methods have and then filter those of our interest
```{r levels,}

carnivores$METHOD <- as.factor(carnivores$METHOD)
levels(carnivores$METHOD)

```

```{r filter method, message= FALSE}

camtrap <- c("Active searching, Camera trap", "Camera trap", "Active searching, Camera trap, Opportunistic", "Active searching, Camera trap, People reports","Arboreal Camera trap","Camera trap, Line transect", "Camera trap, Nest boxes", "Camera trap, Olfactory attraction station, Transect", "Camera trap, Opportunistic", "Camera trap, Opportunistic, Scat sampling", "Camera trap, Sign", "Olfactory attraction station, Camera trap")

camtrapcarn <-  filter(carnivores, METHOD %in% camtrap)

#filter to occurence
carn <- filter(camtrapcarn, OCCUR == 1)

```

### Species filter
```{r levels  species,}

carn$SPECIES <- as.factor(carn$SPECIES)
levels(carn$SPECIES)

```

```{r sp filter,}
spname <-  c("Cerdocyon thous", "Herpailurus yagouaroundi",
         "Leopardus pardalis", "Leopardus tigrinus", "Leopardus wiedii")

# Filter

sp <- filter(carn, SPECIES %in% spname)

```

###Vector converter
```{r vector,}

sp_v <- sp %>% 
  tidyr::drop_na(LONG_X, LAT_Y) %>% 
  dplyr::mutate(lon = LONG_X, lat = LAT_Y) %>% 
  sf::st_as_sf(coords = c("lon", "lat"), crs = 4326)
sp_v

plot(sp_v$geometry, pch = 20)
```
### 1 km Hexagons
```{r Hex,}
br <- rnaturalearth::ne_countries(country = "Brazil", returnclass = "sf")
br

br_hex <- sf::st_make_grid(br, cellsize = 1, square = FALSE) %>% 
  sf::st_as_sf()

br_hex %>%  plot

```

```{r species one by one,}

pardalis <- dplyr::filter(sp, SPECIES == "Leopardus pardalis")
jaguarundi <- dplyr::filter(sp, SPECIES == "Herpailurus yagouaroundi")
tigrinus <- dplyr::filter(sp, SPECIES == "Leopardus tigrinus")
wiedii <- dplyr::filter(sp, SPECIES == "Leopardus wiedii")
cachorro <- dplyr::filter(sp, SPECIES == "Cerdocyon thous")

```

```{r species vectors,}
pardalisv <- pardalis %>% 
  tidyr::drop_na(LONG_X, LAT_Y) %>% 
  dplyr::mutate(lon = LONG_X, lat = LAT_Y) %>% 
  sf::st_as_sf(coords = c("lon", "lat"), crs = 4326)


jaguarundiv <- jaguarundi %>% 
  tidyr::drop_na(LONG_X, LAT_Y) %>% 
  dplyr::mutate(lon = LONG_X, lat = LAT_Y) %>% 
  sf::st_as_sf(coords = c("lon", "lat"), crs = 4326)


tigrinusv <- tigrinus %>% 
  tidyr::drop_na(LONG_X, LAT_Y) %>% 
  dplyr::mutate(lon = LONG_X, lat = LAT_Y) %>% 
  sf::st_as_sf(coords = c("lon", "lat"), crs = 4326)

wiediiv <- wiedii %>% 
  tidyr::drop_na(LONG_X, LAT_Y) %>% 
  dplyr::mutate(lon = LONG_X, lat = LAT_Y) %>% 
  sf::st_as_sf(coords = c("lon", "lat"), crs = 4326)

cachorrov <- cachorro %>% 
  tidyr::drop_na(LONG_X, LAT_Y) %>% 
  dplyr::mutate(lon = LONG_X, lat = LAT_Y) %>% 
  sf::st_as_sf(coords = c("lon", "lat"), crs = 4326)

```

```{r species count in Hex, message=FALSE}
sp_hex <- br_hex %>% 
  dplyr::mutate(pardalis = sf::st_intersects(x = ., pardalisv) %>% lengths())%>%   
  dplyr::mutate(jaguarundi = sf::st_intersects(x = ., jaguarundiv) %>% lengths()) %>% 
  dplyr::mutate(tigrinus = sf::st_intersects(x = ., tigrinusv) %>% lengths()) %>% 
  dplyr::mutate(wiedii = sf::st_intersects(x = ., wiediiv) %>% lengths()) %>% 
  dplyr::mutate(cachorro = sf::st_intersects(x = ., cachorrov) %>% lengths()) 
```

```{r landcover zonal,}
landvalue <- raster::extract(x= landcover, y= br_hex, fun= mean, na.rm= TRUE)
```

###create datafram

```{r dataframe}
dados_sp <- sp_hex
dados_sp$landmean <- landvalue

#List eliminated
dados_sp$x <- NULL
write.table(dados_sp ,file="dados_sp.csv",row.names = F,quote=F,col.names=T,sep="\t")

```

```{r}
dados_carn <- readr::read_csv(here::here("01_communities", "dados_sp.csv"))
```

```{r statistic, }
#Hipothesis
dados_carn$pardalis <- as.factor(dados_carn$pardalis)

mod <- ordinal::clm(formula= pardalis ~ jaguarundi + tigrinus+ wiedii+ cachorro, data = dados_carn)

summary(mod)

gg <- ggstatsplot::ggcoefstats(
  x = mod,
  stats.label.color = "black",
  title = "cumulative link model (clm)"
  ) +
  ggplot2::labs(x = "logit regression coefficient", y = NULL)

```

